# Generated by Django 6.1 on 2026-08-28 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('semestre', models.IntegerField(choices=[(1, '1er semestre'), (2, '2do semestre')])),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-anio', '-semestre'],
                'unique_together': {('anio', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('origen', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], max_length=10)),
                ('fecha', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_facturado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado_facturacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('cobrado', 'Cobrado')], default='pendiente', max_length=10)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.periodo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.tipoevento')),
            ],
        ),
    ]
