# Generated by Django 6.1 on 2026-08-30 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_itemprecio_evento_estado_evento_presupuesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='cantidad_personas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='cliente',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='evento',
            name='expediente',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='evento',
            name='nro_comprobante',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='evento',
            name='nro_factura',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='evento',
            name='nro_recibo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='evento',
            name='solicitante',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='evento',
            name='origen',
            field=models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='interno', max_length=10),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eventos.tipoevento'),
        ),
        migrations.CreateModel(
            name='DetalleCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manteleria', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('materia_prima', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('personal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('planilla', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('varios', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_costo', to='eventos.evento')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eventos.tiposervicio'),
        ),
    ]
