# Generated by Django 6.1 on 2026-08-30 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_tiposervicio_evento_cantidad_personas_evento_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemprecio',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='itemprecio',
            name='actualizado',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='cantidad_personas_celiaco',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='lugar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='recargo_celiaco_por_persona',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='servicios_incluidos',
            field=models.TextField(blank=True, help_text='Ej: Bebida (agua, gaseosa, vino), vajilla y mantelería, servicio de mozos, cocina, mobiliario.'),
        ),
        migrations.CreateModel(
            name='OpcionMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Opción 1', max_length=50)),
                ('detalle_menu', models.TextField(help_text='Un plato por línea.')),
                ('precio_por_persona', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.IntegerField(default=0)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='eventos.presupuesto')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='opcion_elegida',
            field=models.ForeignKey(blank=True, help_text='Se completa cuando el cliente confirma cuál opción eligió.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eventos.opcionmenu'),
        ),
        migrations.DeleteModel(
            name='ItemPresupuesto',
        ),
    ]
