# Generated by Django 6.1 on 2026-08-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_itemprecio_options_itemprecio_actualizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='servicios_incluidos',
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='otros_extras',
            field=models.TextField(blank=True, help_text='Cualquier extra que no esté en la lista de arriba.'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='extras_incluidos',
            field=models.ManyToManyField(blank=True, related_name='presupuestos', to='eventos.extra'),
        ),
    ]
