# Generated by Django 6.1 on 2026-08-31 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_extra_remove_presupuesto_servicios_incluidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto_asignado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('servicios_adicionales_horas_extra', models.IntegerField(blank=True, null=True)),
                ('raciones_comun', models.IntegerField(blank=True, null=True)),
                ('raciones_vegetariano', models.IntegerField(blank=True, null=True)),
                ('raciones_celiaco', models.IntegerField(blank=True, null=True)),
                ('resumen_ejecutivo', models.TextField(blank=True)),
                ('objetivos', models.TextField(blank=True)),
                ('logros_destacados', models.TextField(blank=True)),
                ('desafios_proximo_periodo', models.TextField(blank=True)),
                ('actualizado', models.DateField(auto_now=True)),
                ('periodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informe_gestion', to='eventos.periodo')),
            ],
        ),
    ]
